version: "3.9"

services:
  app:
    build: .
    container_name: sol_app
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DB_HOST: db
      DB_NAME: solmmerce_bd
      DB_USERNAME: sol_user
      DB_PASSWORD: sol_pass
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: sol_db
    environment:
      POSTGRES_DB: solmmerce_bd
      POSTGRES_USER: sol_user
      POSTGRES_PASSWORD: sol_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
